# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the
# Fibonacci sequence whose values do not exceed four million, find the sum
# of the even-valued terms.
#
# Answer: 4613732
#

max = 4000000
out = 0
a = 1
b = 0

while a + b < max:
    # Use Fibonacci sequence A(n+2) = A(n+1) + A(n)
    a, b = b, a + b

    # Check for even valued term
    if b % 2 == 0:
        out += b

print(out)
