public class a02 {
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the
	 * Fibonacci sequence whose values do not exceed four million, find the sum
	 * of the even-valued terms.
	 */
	public static void main(String[] args) {

		// Setup initial values
		final int limit = 4000000;
		int totalValue = 0;
		int xValue, yValue, zValue = 0;
		yValue = zValue;
		xValue = 1;

		while (yValue + xValue < limit) {
			// Create the Fibonacci sequence
			zValue = yValue + xValue;
			xValue = yValue;
			yValue = zValue;

			if (zValue % 2 == 0)
				// Add even values to totalValue
				totalValue += zValue;
		}

		// Output total value of all even numbers in sequence under the limit.
		System.out.println(zValue);
		System.out.println(totalValue);
	}

}
